version: '3.4'

services:
  db:
    image: 'postgres:latest'
    ports:
      - "6543:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    ports: 
      - "8000:8000"
    volumes: 
      - .:/build/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - .env
  
  db_test:
    image: 'postgres:latest'
    ports:
      - "6000:5432"
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data_test:/var/lib/postgresql/data

volumes:
  pg_data: null
  pg_data_test: null